import Footer from "@/components/Footer/Footer";
import NavigationBar from "@/components/NavigationBar/NavigationBar";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Home | Digital Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} md:min-h-[93vh] min-h-screen bg-[#F1F3F7]`}
      >
        <Providers>
          <NavigationBar />
          <div className="md:max-w-[1480px] md:mx-auto py-8 -z-50">
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
